### ISSUE TITLE
EPIC - Custom GeoWave Heatmap for Spatial Binning Aggregations and Statistics

### ISSUE THREAD

**Issue by mzagorskirs** [mzagorskirs/geowave#3]
**Purpose/summary of Epic:** Get up-to-speed with GeoServer by way of examples and hands-on development, which will work toward a goal of creating an aggregation heatmap in GeoWave.

**Tasks:**
- 1: Spike/learning experience: Develop a render transformation GeoServer plugin.  The plugin should be able to translate the data (e.g. from vector <-> raster, or vector -> vector) and shift the data by a specified amount of degrees.  Data could be a shapefile, but probably best to use the GDELT vector data.  Code should be developed within a personal repo as a plugin for GeoServer using Java.  Through this task, the developer will get up-to-speed with creating GeoServer plugins and creating render transforms.
- 2: Look at GeoServer example of heatmap and get it working using GDELT data, with the ultimate goal of writing own heatmap plugin in JAVA.
- 3 - 5: The ultimate goal: the heatmap plugin that GeoServer uses queries _all_ the data in GeoWave, however, we want to use GeoWave's aggregations (and eventually statistics) in the heatmap query.
- 6: Develop GeoWave customization of the heapmap process using spatial binning statistics.
- 7 - 8: User preferences and automations.
- 9: Add spatial constraints to query builders to minimize processing time.
- 10: Configurations to handle tiling in GeoServer.
- 11: Convert to WGS84.
- 12: Finalize integration tests.

**Definition of Done:** This GitHub issue will be considered done when these items have been met: 

- [x] Task 1 - GeoServer plugin that shifts vector data by a specified amount of degrees.
- [x] Task 2 - Local run of GeoServer heatmap example using GDELT data.
- [x] Task 3 - Develop an Integration Test that will test the application of the Heatmap SLD to some created unit test data.
- [x] Task 4 - Port over the GeoTools version of the heatmap process and research spatial binning methods in GeoWave. 
- [x] Task 5 - Develop GeoWave version/customization of the heatmap process using spatial binning aggregation: field sum and field count.
- [x] Task 6 - Develop GeoWave customization of the heapmap process using spatial binning statistics.
- [x] Task 7 - Add more parameters to SLD for user preferences.
- [x] Task 8 - Add a dynamic GeoHash algorithm.
- [x] Task 9 - Add spatial constraints to query builders for improved runtime performance.
- [x] Task 10 - Finalize integration tests and prepare to push PR.
- [x] Task 11 - Convert to WGS84 (for spatial binning and GeoServerIngestIT).
- [x] **MILESTONE** - PR pushed, reviewed and merged.
- [ ] Task 12 - Handle tiling.  This will be implemented after the initial PR is merged.

**Tips for getting started:** 

- Task 1 and 2 - see Resources section below.  And also, a close example would be: https://docs.geoserver.org/latest/en/user/styling/sld/extensions/rendering-transform.html#group-candidate-selection
- Task 3 - Similar to the .sld Subsample https://github.com/locationtech/geowave/blob/master/examples/data/slds/SubsamplePoints.sld#L15  as defined in GeoWave here: [https://github.com/locationtech/geowave/blob/master/extensions/adapters/vector/src[…]ocationtech/geowave/adapter/vector/plugin/SubsampleProcess.java](https://github.com/locationtech/geowave/blob/master/extensions/adapters/vector/src/main/java/org/locationtech/geowave/adapter/vector/plugin/SubsampleProcess.java)
- Task 3 - using hints: [https://github.com/locationtech/geowave/blob/master/extensions%2Fadapters%2Fvector[…]ave%2Fadapter%2Fvector%2Fplugin%2FGeoWaveFeatureCollection.java](https://github.com/locationtech/geowave/blob/master/extensions%2Fadapters%2Fvector%2Fsrc%2Fmain%2Fjava%2Forg%2Flocationtech%2Fgeowave%2Fadapter%2Fvector%2Fplugin%2FGeoWaveFeatureCollection.java#L223-L237)

**Resources:** 

- [Task 1 - render transform](https://docs.geoserver.org/latest/en/user/styling/sld/extensions/rendering-transform.html)
- [Task 2 - heat map](https://docs.geoserver.org/latest/en/user/styling/sld/extensions/rendering-transform.html#heatmap-generation)

**Timeframe:** 

- 1 - 2 tasks per sprint or more as time allows.

**Comment by mzagorskirs** [comment]
Project ended early (this week); any remaining items for this epic will not be finished due to no more time/funding.
